---
title: ""
output: html_document
---
<br>

### Poster  
The final third of the course is an opportunity to explore, in depth, an environmental management challenge of their choice, do a meta-analysis, and present in a poster session (learning outcomes 5 & 6).  Meta-analyses and data aggregation across studies are the gold-standard evidence-based decision making tool in most disciplines of science including health, clinical research, environmental science, and ecology and evolution. This is a group endeavour for sets of students with similiar interests to apply the emc2 and rers thinking to a topic of their choice, develop and present and analysis, and share with the class.  

First class in final week - poster session for students in class only. Poster DRAFT 'due' this day - HOWEVER delay judging until the final class that week.  The DRAFT poster session will be for you to review and offer feedback to other group posters - peer-to-peer. You are absolutely welcome to revise from that advice but must provide, in person, the final poster for judging in the last class (Nov 28th).  

Please list all group members on poster, print to PDF, and also have one group member please submit to [turnitin.com](https://www.turnitin.com).    

SUMMARY - this is a chance to get feedback, revise, and get an **automatic extension** to the final class on Nov 28th at 11:59pm  if you would like to take advantage of it.  It also provides an opportunity to practice poster presentations and answering questions before you get graded with colleagues.  


**Marking key/rebric total to 20**  
Clarity of visuals/5    
Transparent science presented/5  
Effective scientific synthesis/5    
Conclusions & implications sufficiently developed/5  

Explanations   
Clarity - easy to see, colours attractive and with good contrast, consistent palette and theme, fonts legible and easy to read, content organized in a logical and accessible manner  

transparent science - show and explain the key elements of your synthesis work - provide enough info for others to replicate  

effective synthesis - did you put together the best, most representative data from your set of studies, did the data you collect match the purpose of the project, did you put together/compile data with meaning and purpose to test bio4enviro idea, was there a test statistic and plot that was at an appropriate level of science and complexity consistent with a 4000-level offering    

conclusions & implications - flow from data, actionable, implications of what we know and what we do not know, directions for change, better science, or bio4enviro principles or better tools

**Guidelines**  
Abstract is preferred but decide based on room you have on poster.  I recommend full sentences for Intro and Methods. However, you are welcome to explore tables and other short formats such as bullets to communicate other findings.  Each poster should also have an organizing statement (purpose or hypothesis or key question you are examining).  Use the ten simple rules for posters we discussed in class.  There must also be at least one data plot on the poster showing what did you compiled to do you meta-work.  I also like a map as a second visual showing where all the studies were completed that you used in your synthesis.  

There is a lot of variation in scientific posters, and I do not want to limit your science or creativity.  However, I will be using the marking key shown above - it is general and captures the salient elements of all effective posters.  

Please include a **contribution table** on poster using initials of each person listing the work each individual completed as part of the synthesis.  Also, list all authors after title at top of poster.  

